Repository Leets-Official/BookMark-BE, pull requests merged in 2025-08, with the labels that each got.

#68 Feat #60 카테고리 반환 시 썸네일 추가
  src/main/java/leets/bookmark/domain/bookmark/domain/repository/BookmarkRepository.java
  src/main/java/leets/bookmark/domain/bookmark/domain/repository/BookmarkTagMappingRepository.java
  src/main/java/leets/bookmark/domain/bookmark/domain/service/BookmarkGetService.java
  src/main/java/leets/bookmark/domain/category/application/dto/response/CategoryResponse.java
  src/main/java/leets/bookmark/domain/category/application/exception/CategoryErrorCode.java
  src/main/java/leets/bookmark/domain/category/application/exception/CategoryHasBookmarksException.java
  src/main/java/leets/bookmark/domain/category/application/mapper/CategoryMapper.java
  src/main/java/leets/bookmark/domain/category/application/usecase/CategoryUseCaseImpl.java
  src/main/java/leets/bookmark/domain/tag/application/exception/TagErrorCode.java
  src/main/java/leets/bookmark/domain/tag/application/exception/TagHasBookmarksException.java
  src/main/java/leets/bookmark/domain/tag/application/usecase/TagUseCaseImpl.java
Labels: Feat

#72 Feat #71 카테고리 태그 반환 시 플랫폼 추가
  src/main/java/leets/bookmark/domain/bookmark/application/mapper/BookmarkCategoryMapper.java
  src/main/java/leets/bookmark/domain/category/application/dto/response/CategoryWithTagResponse.java
  src/main/java/leets/bookmark/domain/category/application/mapper/CategoryMapper.java
  src/main/java/leets/bookmark/domain/category/application/usecase/CategoryUseCaseImpl.java
Labels: Feat

#73 Feat #70 북마크 필터에 다중 플랫폼 선택 기능 추가
  src/main/java/leets/bookmark/domain/bookmark/application/dto/request/BookmarkSearchCondition.java
  src/main/java/leets/bookmark/domain/bookmark/application/dto/request/BookmarkSearchRequest.java
  src/main/java/leets/bookmark/domain/bookmark/application/mapper/BookmarkSearchConditionMapper.java
  src/main/java/leets/bookmark/domain/bookmark/application/usecase/BookmarkUseCaseImpl.java
  src/main/java/leets/bookmark/domain/bookmark/domain/repository/BookmarkRepositoryImpl.java
Labels: Feat

#75 Feat #74 플랫폼 조회 기능 추가
  src/main/java/leets/bookmark/domain/bookmark/application/dto/response/BookmarkPlatformResponse.java
  src/main/java/leets/bookmark/domain/bookmark/application/mapper/BookmarkPlatformMapper.java
  src/main/java/leets/bookmark/domain/bookmark/application/usecase/BookmarkUseCase.java
  src/main/java/leets/bookmark/domain/bookmark/application/usecase/BookmarkUseCaseImpl.java
  src/main/java/leets/bookmark/domain/bookmark/domain/repository/BookmarkRepository.java
  src/main/java/leets/bookmark/domain/bookmark/domain/service/BookmarkGetService.java
  src/main/java/leets/bookmark/domain/bookmark/presentation/BookmarkPlatformController.java
  src/main/java/leets/bookmark/domain/bookmark/presentation/BookmarkResponseMessage.java
  src/main/java/leets/bookmark/domain/category/application/dto/response/CategoryWithTagResponse.java
  src/main/java/leets/bookmark/domain/category/application/mapper/CategoryMapper.java
Labels: Feat

#77 feat #62 파일이 널값이면 저장이 되지 않게 수정
  src/main/java/leets/bookmark/domain/bookmark/application/dto/request/BookmarkSaveRequest.java
Labels: Bug Fix

#81 Feat #80 Pre-signed URL 파일 확장자 추출 메소드 로직 수정
  src/main/java/leets/bookmark/domain/file/application/usecase/FileUseCase.java
  src/main/java/leets/bookmark/domain/file/domain/entity/enums/FileType.java
Labels: Bug Fix

#89 Feat #84 S3 업로드 api 추가
  src/main/java/leets/bookmark/domain/bookmark/application/dto/request/BookmarkSaveRequest.java
  src/main/java/leets/bookmark/domain/bookmark/application/dto/request/BookmarkUpdateRequest.java
  src/main/java/leets/bookmark/domain/bookmark/application/usecase/BookmarkUseCaseImpl.java
  src/main/java/leets/bookmark/domain/bookmark/domain/service/BookmarkUpdateService.java
  src/main/java/leets/bookmark/domain/file/application/exception/FileErrorCode.java
  src/main/java/leets/bookmark/domain/file/application/exception/S3UploadException.java
  src/main/java/leets/bookmark/domain/file/application/mapper/FileMapper.java
  src/main/java/leets/bookmark/domain/file/application/usecase/FileUseCase.java
  src/main/java/leets/bookmark/domain/file/domain/entity/enums/FileType.java
  src/main/java/leets/bookmark/domain/file/domain/service/FileUpdateService.java
  src/main/java/leets/bookmark/domain/file/domain/service/S3UploadService.java
  src/main/java/leets/bookmark/domain/file/presentation/FileController.java
  src/main/java/leets/bookmark/domain/file/presentation/FileResponseCode.java
  src/main/java/leets/bookmark/global/config/AmazonS3Config.java
Labels: Feat

#95 Hotfix #94 카카오 리다이렉션 설정 수정
  src/main/java/leets/bookmark/global/auth/oauth2/application/usecase/OAuth2UseCase.java
  src/main/java/leets/bookmark/global/auth/oauth2/application/usecase/OAuth2UseCaseImpl.java
  src/main/java/leets/bookmark/global/auth/oauth2/service/KakaoGetService.java
  src/main/java/leets/bookmark/global/auth/presentation/AuthController.java
Labels: HotFix

#92 fix #91 파일 저장 버그 수정
  src/main/java/leets/bookmark/domain/file/application/usecase/FileUseCase.java
  src/main/java/leets/bookmark/domain/file/domain/service/S3UploadService.java
Labels: Bug Fix

#93 fix #90 카카오톡 알림 버그 수정
  src/main/java/leets/bookmark/domain/notification/domain/service/KakaoNotificationService.java
  src/main/resources/application.yml
Labels: Bug Fix

#99 Feat #96 이미지 url을 통한 파일 반환 기능 추가
  src/main/java/leets/bookmark/domain/file/application/dto/response/FetchedThumbnailResponse.java
  src/main/java/leets/bookmark/domain/file/application/exception/FileErrorCode.java
  src/main/java/leets/bookmark/domain/file/application/exception/ImageFetchException.java
  src/main/java/leets/bookmark/domain/file/application/mapper/FileMapper.java
  src/main/java/leets/bookmark/domain/file/application/usecase/FileUseCase.java
  src/main/java/leets/bookmark/domain/file/domain/entity/enums/FileType.java
  src/main/java/leets/bookmark/domain/file/presentation/FileController.java
Labels: Feat

#98 feat 97 메모 수정기능 추가
  src/main/java/leets/bookmark/domain/bookmark/application/exception/BookmarkErrorCode.java
  src/main/java/leets/bookmark/domain/bookmark/application/exception/BookmarkUpdateFieldEmptyException.java
  src/main/java/leets/bookmark/domain/bookmark/application/mapper/BookmarkMapper.java
  src/main/java/leets/bookmark/domain/bookmark/application/usecase/BookmarkUseCaseImpl.java
  src/main/java/leets/bookmark/domain/bookmark/domain/entity/Bookmark.java
Labels: Feat
