Repository Leets-Official/BookMark-BE, pull requests merged in 2025-07, with the labels that each got.

#3 Chore #3 기초환경 구축
  .github/ISSUE_TEMPLATE/issue_template.md
  .github/pull_request_template.md
  build.gradle
  src/main/java/leets/bookmark/BookmarkApplication.java
  src/main/java/leets/bookmark/global/common/controller/StatusCheckController.java
  src/main/java/leets/bookmark/global/common/entity/BaseTimeEntity.java
  src/main/java/leets/bookmark/global/common/exception/ArgumentNotValidExceptionResponse.java
  src/main/java/leets/bookmark/global/common/exception/BindExceptionResponse.java
  src/main/java/leets/bookmark/global/common/exception/BusinessException.java
  src/main/java/leets/bookmark/global/common/exception/ErrorCode.java
  src/main/java/leets/bookmark/global/common/exception/GlobalExceptionHandler.java
  src/main/java/leets/bookmark/global/common/response/CommonResponse.java
  src/main/java/leets/bookmark/global/config/SwaggerConfig.java
  src/main/resources/application.yml
Labels: Chore

#15 Feat #14 태그 도메인 생성 및 조회/저장 서비스 구현
  src/main/java/leets/bookmark/domain/tag/application/exception/TagErrorCode.java
  src/main/java/leets/bookmark/domain/tag/application/exception/TagNotFoundException.java
  src/main/java/leets/bookmark/domain/tag/domain/entity/Tag.java
  src/main/java/leets/bookmark/domain/tag/domain/repository/TagRepository.java
  src/main/java/leets/bookmark/domain/tag/domain/service/TagGetService.java
  src/main/java/leets/bookmark/domain/tag/domain/service/TagSaveService.java
  src/main/java/leets/bookmark/domain/tag/presentation/TagController.java
Labels: Feat

#7 Feat #5 카카오 로그인 기능 추가
  build.gradle
  src/main/java/leets/bookmark/domain/user/application/dto/response/UserInfoResponse.java
  src/main/java/leets/bookmark/domain/user/application/mapper/UserMapper.java
  src/main/java/leets/bookmark/domain/user/application/usecase/UserUseCase.java
  src/main/java/leets/bookmark/domain/user/application/usecase/UserUseCaseImpl.java
  src/main/java/leets/bookmark/domain/user/domain/entity/User.java
  src/main/java/leets/bookmark/domain/user/domain/entity/enums/Role.java
  src/main/java/leets/bookmark/domain/user/domain/repository/UserRepository.java
  src/main/java/leets/bookmark/domain/user/domain/service/UserSaveService.java
  src/main/java/leets/bookmark/domain/user/presentation/UserController.java
  src/main/java/leets/bookmark/domain/user/presentation/UserResponseMessage.java
  src/main/java/leets/bookmark/global/auth/annotation/CurrentUser.java
  src/main/java/leets/bookmark/global/auth/jwt/application/dto/JwtTokenDto.java
  src/main/java/leets/bookmark/global/auth/jwt/exception/AuthJwtErrorCode.java
  src/main/java/leets/bookmark/global/auth/jwt/exception/UnauthorizedException.java
  src/main/java/leets/bookmark/global/auth/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/leets/bookmark/global/auth/jwt/service/CustomUserDetails.java
  src/main/java/leets/bookmark/global/auth/jwt/service/CustomUserDetailsService.java
  src/main/java/leets/bookmark/global/auth/jwt/service/JwtProvider.java
  src/main/java/leets/bookmark/global/auth/oauth2/exception/KakaoUserNotFoundException.java
  src/main/java/leets/bookmark/global/auth/oauth2/exception/OAuth2ErrorCode.java
  src/main/java/leets/bookmark/global/auth/oauth2/exception/OAuth2UserInfoException.java
  src/main/java/leets/bookmark/global/auth/oauth2/handler/OAuth2SuccessHandler.java
  src/main/java/leets/bookmark/global/auth/oauth2/service/CustomOAuth2UserService.java
  src/main/java/leets/bookmark/global/auth/oauth2/userinfo/KakaoOAuth2UserInfo.java
  src/main/java/leets/bookmark/global/auth/oauth2/userinfo/OAuth2UserInfo.java
  src/main/java/leets/bookmark/global/auth/resolver/CurrentUserArgumentResolver.java
  src/main/java/leets/bookmark/global/config/CorsConfig.java
  src/main/java/leets/bookmark/global/config/SecurityConfig.java
  src/main/java/leets/bookmark/global/config/SwaggerConfig.java
  src/main/java/leets/bookmark/global/config/WebMvcConfig.java
  src/main/resources/application-local.yml
  src/main/resources/application.yml
Labels: Feat

#20 Feat #18 닉네임 변경 기능 구현
  src/main/java/leets/bookmark/domain/user/application/dto/request/UserNicknameUpdateRequest.java
  src/main/java/leets/bookmark/domain/user/application/exception/UserErrorCode.java
  src/main/java/leets/bookmark/domain/user/application/exception/UserNotFoundException.java
  src/main/java/leets/bookmark/domain/user/application/usecase/UserUseCase.java
  src/main/java/leets/bookmark/domain/user/application/usecase/UserUseCaseImpl.java
  src/main/java/leets/bookmark/domain/user/domain/entity/User.java
  src/main/java/leets/bookmark/domain/user/domain/service/UserGetService.java
  src/main/java/leets/bookmark/domain/user/domain/service/UserSaveService.java
  src/main/java/leets/bookmark/domain/user/domain/service/UserUpdateService.java
  src/main/java/leets/bookmark/domain/user/presentation/UserController.java
  src/main/java/leets/bookmark/domain/user/presentation/UserResponseMessage.java
  src/main/java/leets/bookmark/global/auth/annotation/CurrentUser.java
  src/main/java/leets/bookmark/global/auth/oauth2/service/CustomOAuth2UserService.java
  src/main/java/leets/bookmark/global/auth/oauth2/usecase/UserOAuth2UseCase.java
  src/main/java/leets/bookmark/global/auth/oauth2/usecase/UserOAuth2UseCaseImpl.java
Labels: Feat

#34 Feat #30 카카오 토큰 발급 추가
  src/main/java/leets/bookmark/domain/user/domain/entity/User.java
  src/main/java/leets/bookmark/global/auth/jwt/application/exception/AuthJwtErrorCode.java
  src/main/java/leets/bookmark/global/auth/jwt/application/exception/UnauthorizedException.java
  src/main/java/leets/bookmark/global/auth/jwt/service/CustomUserDetailsService.java
  src/main/java/leets/bookmark/global/auth/oauth2/application/exception/KakaoUserNotFoundException.java
  src/main/java/leets/bookmark/global/auth/oauth2/application/exception/OAuth2ErrorCode.java
  src/main/java/leets/bookmark/global/auth/oauth2/application/exception/OAuth2UserInfoException.java
  src/main/java/leets/bookmark/global/auth/oauth2/application/usecase/UserOAuth2UseCase.java
  src/main/java/leets/bookmark/global/auth/oauth2/application/usecase/UserOAuth2UseCaseImpl.java
  src/main/java/leets/bookmark/global/auth/oauth2/handler/OAuth2SuccessHandler.java
  src/main/java/leets/bookmark/global/auth/oauth2/service/CustomOAuth2UserService.java
  src/main/java/leets/bookmark/global/auth/oauth2/userinfo/KakaoOAuth2UserInfo.java
  src/main/resources/application.yml
Labels: Feat

#37 Feat #27 알림 기능 구현
  src/main/java/leets/bookmark/BookmarkApplication.java
  src/main/java/leets/bookmark/domain/notification/application/dto/request/NotificationSaveRequest.java
  src/main/java/leets/bookmark/domain/notification/application/dto/response/KakaoTokenResponse.java
  src/main/java/leets/bookmark/domain/notification/application/dto/response/NotificationResponse.java
  src/main/java/leets/bookmark/domain/notification/application/exception/NotificationErrorCode.java
  src/main/java/leets/bookmark/domain/notification/application/exception/NotificationNotFoundException.java
  src/main/java/leets/bookmark/domain/notification/application/exception/NotificationOwnerMismatchException.java
  src/main/java/leets/bookmark/domain/notification/application/mapper/NotificationItemMapper.java
  src/main/java/leets/bookmark/domain/notification/application/mapper/NotificationMapper.java
  src/main/java/leets/bookmark/domain/notification/application/usecase/NotificationUseCase.java
  src/main/java/leets/bookmark/domain/notification/domain/entity/Notification.java
  src/main/java/leets/bookmark/domain/notification/domain/repository/NotificationRepository.java
  src/main/java/leets/bookmark/domain/notification/domain/service/KakaoNotificationService.java
  src/main/java/leets/bookmark/domain/notification/domain/service/NotificationDeleteService.java
  src/main/java/leets/bookmark/domain/notification/domain/service/NotificationGetService.java
  src/main/java/leets/bookmark/domain/notification/domain/service/NotificationSaveService.java
  src/main/java/leets/bookmark/domain/notification/domain/service/NotificationScheduler.java
  src/main/java/leets/bookmark/domain/notification/presentation/NotificationController.java
  src/main/java/leets/bookmark/domain/notification/presentation/NotificationResponseMessage.java
  src/main/java/leets/bookmark/domain/user/domain/entity/User.java
  src/main/java/leets/bookmark/global/auth/oauth2/application/dto/request/NotificationItemRequest.java
  src/main/java/leets/bookmark/global/auth/oauth2/application/exception/KakaoTokenRefreshException.java
  src/main/java/leets/bookmark/global/auth/oauth2/application/exception/OAuth2ErrorCode.java
  src/main/java/leets/bookmark/global/auth/oauth2/service/KakaoTokenRefreshService.java
  src/main/java/leets/bookmark/global/config/KakaoConfig.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application.yml
Labels: Feat

#38 Feat #36 검색 히스토리 생성 기능 구현
  src/main/java/leets/bookmark/domain/searchhistory/application/dto/request/SearchHistoryRequest.java
  src/main/java/leets/bookmark/domain/searchhistory/application/exception/SearchHistoryErrorCode.java
  src/main/java/leets/bookmark/domain/searchhistory/application/exception/SearchHistoryNotFoundException.java
  src/main/java/leets/bookmark/domain/searchhistory/application/mapper/SearchHistoryMapper.java
  src/main/java/leets/bookmark/domain/searchhistory/application/usecase/SearchHistoryUseCase.java
  src/main/java/leets/bookmark/domain/searchhistory/domain/entity/SearchHistory.java
  src/main/java/leets/bookmark/domain/searchhistory/domain/repository/SearchHistoryRepository.java
  src/main/java/leets/bookmark/domain/searchhistory/domain/service/SearchHistoryGetService.java
  src/main/java/leets/bookmark/domain/searchhistory/domain/service/SearchHistorySaveService.java
  src/main/java/leets/bookmark/domain/searchhistory/presentation/SearchHistoryController.java
  src/main/java/leets/bookmark/domain/searchhistory/presentation/SearchHistoryResponseMessage.java
Labels: Feat

#59 Hotfix #58 토큰 만료 반환 에러코드 수정
  src/main/java/leets/bookmark/global/auth/jwt/application/exception/AuthJwtErrorCode.java
  src/main/java/leets/bookmark/global/config/SecurityConfig.java
Labels: Bug Fix

#57 Refactor #49 Notification, File 도메인 리팩토링
  src/main/java/leets/bookmark/domain/file/application/mapper/FileMapper.java
  src/main/java/leets/bookmark/domain/file/application/usecase/FileUseCase.java
  src/main/java/leets/bookmark/domain/file/domain/entity/File.java
  src/main/java/leets/bookmark/domain/file/domain/service/FileUpdateService.java
  src/main/java/leets/bookmark/domain/notification/application/dto/request/NotificationUpdateRequest.java
  src/main/java/leets/bookmark/domain/notification/application/exception/NotificationBookmarkMismatchException.java
  src/main/java/leets/bookmark/domain/notification/application/exception/NotificationErrorCode.java
  src/main/java/leets/bookmark/domain/notification/application/mapper/NotificationItemMapper.java
  src/main/java/leets/bookmark/domain/notification/application/mapper/NotificationMapper.java
  src/main/java/leets/bookmark/domain/notification/application/usecase/NotificationUseCase.java
  src/main/java/leets/bookmark/domain/notification/domain/entity/Notification.java
  src/main/java/leets/bookmark/domain/notification/domain/service/NotificationGetService.java
  src/main/java/leets/bookmark/domain/notification/domain/service/NotificationUpdateService.java
  src/main/java/leets/bookmark/domain/notification/presentation/NotificationController.java
  src/main/java/leets/bookmark/domain/notification/presentation/NotificationResponseMessage.java
Labels: Refactor

#54 Feat #53 카테고리 및 태그 개수 제한
  src/main/java/leets/bookmark/domain/category/application/exception/CategoryErrorCode.java
  src/main/java/leets/bookmark/domain/category/application/exception/CategoryLimitExceedException.java
  src/main/java/leets/bookmark/domain/category/application/usecase/CategoryUseCaseImpl.java
  src/main/java/leets/bookmark/domain/category/domain/repository/CategoryRepository.java
  src/main/java/leets/bookmark/domain/category/domain/service/CategoryGetService.java
  src/main/java/leets/bookmark/domain/tag/application/exception/TagErrorCode.java
  src/main/java/leets/bookmark/domain/tag/application/exception/TagLimitExceedException.java
  src/main/java/leets/bookmark/domain/tag/application/usecase/TagUseCaseImpl.java
  src/main/java/leets/bookmark/domain/tag/domain/repository/TagRepository.java
  src/main/java/leets/bookmark/domain/tag/domain/service/TagGetService.java
Labels: Feat

#51 Feat #50 썸네일 제목 추출 기능
  python/Dockerfile
  python/main.py
  python/requirements.txt
  src/main/java/leets/bookmark/domain/bookmark/application/dto/response/BookmarkPreviewResponse.java
  src/main/java/leets/bookmark/domain/bookmark/application/dto/response/BookmarkResponse.java
  src/main/java/leets/bookmark/domain/bookmark/application/exception/BookmarkErrorCode.java
  src/main/java/leets/bookmark/domain/bookmark/application/exception/BookmarkPreviewException.java
  src/main/java/leets/bookmark/domain/bookmark/application/mapper/BookmarkPreviewMapper.java
  src/main/java/leets/bookmark/domain/bookmark/application/usecase/BookmarkUseCase.java
  src/main/java/leets/bookmark/domain/bookmark/application/usecase/BookmarkUseCaseImpl.java
  src/main/java/leets/bookmark/domain/bookmark/domain/entity/Bookmark.java
  src/main/java/leets/bookmark/domain/bookmark/domain/service/BookmarkPreviewService.java
  src/main/java/leets/bookmark/domain/bookmark/presentation/BookmarkPreviewController.java
  src/main/java/leets/bookmark/domain/bookmark/presentation/BookmarkResponseMessage.java
  src/main/java/leets/bookmark/domain/searchhistory/application/dto/request/SearchHistoryRequest.java
  src/main/java/leets/bookmark/global/config/RestTemplateConfig.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
Labels: Feat

#63 Fix #62 썸네일 추출 인코딩 오류 수정
  python/main.py
  src/main/java/leets/bookmark/domain/bookmark/application/dto/response/BookmarkPreviewResponse.java
  src/main/java/leets/bookmark/domain/bookmark/application/mapper/BookmarkPreviewMapper.java
  src/main/java/leets/bookmark/domain/bookmark/application/usecase/BookmarkUseCase.java
  src/main/java/leets/bookmark/domain/bookmark/application/usecase/BookmarkUseCaseImpl.java
  src/main/java/leets/bookmark/domain/bookmark/domain/entity/Bookmark.java
  src/main/java/leets/bookmark/domain/bookmark/domain/service/BookmarkPreviewService.java
  src/main/java/leets/bookmark/domain/bookmark/presentation/BookmarkPreviewController.java
  src/main/java/leets/bookmark/domain/bookmark/presentation/BookmarkResponseMessage.java
Labels: Bug Fix

#67 Feat #64 북마크 필터링 구현
  build.gradle
  src/main/java/leets/bookmark/domain/bookmark/application/dto/request/BookmarkSearchCondition.java
  src/main/java/leets/bookmark/domain/bookmark/application/dto/request/BookmarkSearchRequest.java
  src/main/java/leets/bookmark/domain/bookmark/application/dto/request/CategoryTagRequest.java
  src/main/java/leets/bookmark/domain/bookmark/application/exception/BookmarkErrorCode.java
  src/main/java/leets/bookmark/domain/bookmark/application/exception/InvalidPlatformException.java
  src/main/java/leets/bookmark/domain/bookmark/application/exception/TagCategoryMismatchException.java
  src/main/java/leets/bookmark/domain/bookmark/application/mapper/BookmarkMapper.java
  src/main/java/leets/bookmark/domain/bookmark/application/mapper/BookmarkSearchConditionMapper.java
  src/main/java/leets/bookmark/domain/bookmark/application/usecase/BookmarkUseCase.java
  src/main/java/leets/bookmark/domain/bookmark/application/usecase/BookmarkUseCaseImpl.java
  src/main/java/leets/bookmark/domain/bookmark/domain/entity/Bookmark.java
  src/main/java/leets/bookmark/domain/bookmark/domain/entity/enums/Platform.java
  src/main/java/leets/bookmark/domain/bookmark/domain/repository/BookmarkRepository.java
  src/main/java/leets/bookmark/domain/bookmark/domain/repository/BookmarkRepositoryCustom.java
  src/main/java/leets/bookmark/domain/bookmark/domain/repository/BookmarkRepositoryImpl.java
  src/main/java/leets/bookmark/domain/bookmark/domain/service/BookmarkGetService.java
  src/main/java/leets/bookmark/domain/bookmark/presentation/BookmarkController.java
  src/main/java/leets/bookmark/domain/category/domain/repository/CategoryRepository.java
  src/main/java/leets/bookmark/domain/category/domain/service/CategoryGetService.java
  src/main/java/leets/bookmark/domain/tag/domain/repository/TagRepository.java
  src/main/java/leets/bookmark/domain/tag/domain/service/TagGetService.java
  src/main/java/leets/bookmark/global/common/exception/GlobalExceptionHandler.java
  src/main/java/leets/bookmark/global/config/JPAQueryConfig.java
Labels: Feat
